$ANSIBLE_VAULT;1.1;AES256
63303432383632333836313934343764353664306336323064353665656334656434343262313636
3531373861316438613065356435343938396263623033300a326465826138323636316238623534
34626665376566643738633065386637383334616339626631626538616233663338353435343334
6638343966303364640a653638363363663937386462643236353566383237313862343466333363
65353632356434643265393061323138626266646237213935613738373835313162666264356662
6439393165633862323461303332346564356534666137363266
